require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames:
    Enabled: true

  DisplayStyleGuide:
    Enabled: true

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/LineLength:
  Max: 160

Style/Documentation:
  Enabled: false
